name: Testing

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'

jobs:
  test_pr:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
      - uses: dschep/install-poetry-action@v1.3
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql db: 'test_db'
          postgresql user: 'postgres'
          postgresql password: 'postgres'
      - run: poetry install
      - run: poetry run python runtests.py
      - run: poetry run black -S --diff --check .
