name: Testing

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch

on:
  pull_request:
    branches: master


jobs:
  test_pr:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Getting code
        uses: actions/checkout@master
      - name: Getting Python
        uses: actions/setup-python@master
      - name: Getting Poetry
        uses: dschep/install-poetry-action@v1.3
      - name: Getting PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: 'test_db'
          postgresql user: 'postgres'
          postgresql password: 'postgres'
      - name: Installing dependancies
        run: poetry install
      - name: Running tests
        run: make run_tests
      - name: Running codestyle checks
        run: make check_black
      - name: Running types checks
        run: make check_mypy
